[package]
name = "siglus_scene_vm"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
anyhow.workspace = true
clap.workspace = true
bytemuck.workspace = true
image.workspace = true
log.workspace = true
env_logger.workspace = true
kira.workspace = true
chrono.workspace = true
ab_glyph = "0.2.32"
ttf-parser = "0.25.1"
encoding_rs = "0.8"
eluna = { package = "eluna_rs", version = "0.1.0" }
siglus_omv_decoder = { path = "../siglus_omv_decoder" }
na_mpeg2_decoder = { path = "../na_mpeg2_decoder" }

siglus_assets = { path = "../siglus_assets" }
shion-xfile = { path = "../shion-xfile" }

wgpu.workspace = true
winit.workspace = true
pollster.workspace = true
raw-window-handle = "0.6"
egui = "0.28.1"
egui-wgpu = "0.28.1"



[[bin]]
name = "siglus_engine"
path = "src/bin/siglus_engine.rs"

[[bin]]
name = "mesh_asset_tool"
path = "src/bin/mesh_asset_tool.rs"

[target.'cfg(not(all(target_arch = "wasm32", target_os = "unknown")))'.dependencies]
ureq = "2.10"
walkdir = "2"
fearless_simd = "0.7.0"

[target.'cfg(target_os = "android")'.dependencies]
ndk-context = "0.1.1"
winit = { workspace = true, features = ["android-game-activity"] }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
wgpu = { workspace = true, features = ["webgl"] }
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["console", "Window", "Document", "Element", "HtmlCanvasElement", "HtmlElement"] }
web-time = "1.1"
console_error_panic_hook = "0.1"
getrandom_02 = { package = "getrandom", version = "0.2.17", features = ["js"] }
getrandom_03 = { package = "getrandom", version = "0.3.4", features = ["wasm_js"] }

[features]
default = []
avx512-mipmap = []
